#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# authentication_token:
#     path: /authentication_token
#     methods: ['POST']

authentication_token:
    path: /api/login
    methods: ['POST']